[2021-12-09 08:02:45,647] {processor.py:163} INFO - Started process (PID=412) to work on /opt/airflow/dags/example.py
[2021-12-09 08:02:45,664] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-09 08:02:45,681] {logging_mixin.py:109} INFO - [2021-12-09 08:02:45,676] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-09 08:03:50,383] {processor.py:163} INFO - Started process (PID=436) to work on /opt/airflow/dags/example.py
[2021-12-09 08:03:50,781] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-09 08:03:50,844] {logging_mixin.py:109} INFO - [2021-12-09 08:03:50,827] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-09 08:04:22,448] {logging_mixin.py:109} INFO - [2021-12-09 08:04:22,313] {timeout.py:36} ERROR - Process timed out, PID: 436
[2021-12-09 08:04:23,695] {logging_mixin.py:109} INFO - [2021-12-09 08:04:22,456] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 72, in <module>
    from . import numeric
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/numeric.py", line 23, in <module>
    from . import shape_base
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/shape_base.py", line 13, in <module>
    from . import fromnumeric as _from_nx
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 15, in <module>
    from . import _methods
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/_methods.py", line 12, in <module>
    from numpy.core import _exceptions
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/_exceptions.py", line 119, in <module>
    class TooHardError(RuntimeError):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/example.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#reducing-dag-complexity, PID: 436
[2021-12-09 08:04:25,874] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example.py
[2021-12-09 08:04:25,944] {processor.py:171} INFO - Processing /opt/airflow/dags/example.py took 35.957 seconds
